### ISSUE TITLE
Labeling data

### ISSUE THREAD

**Issue by erfannoury** [trenditter/classifier#1]
I think it is hard and extensive to label Twitter data. However, for election tweets, I used something called distance supervision to train a classifier and it's results weren't too bad. I selected a set hashtags, labeled each one using the classes that I had, and then used those labels as ground truth labels for the actual tweets (which contained those hashtags). I know that this is noisy labeling, but with a large collection of data this problem can be mitigated.

**Comment by mavahedinia** [comment]
well this is great! here we have collected 26,486,537 tweets, therefore we can test your method on our dataset.

In addition, I think this method has a bug, for instance for #الف_مثل_استاد there are some spam tweets, but it was used to inform people about "Taheri"! so they may be labeled as spam while they are "news" tweets!

shall we continue using email or some IM platforms?

**Comment by erfannoury** [comment]
Yeah, that's the problem and what makes this a hard task.
We can move to email. {username}@gmail.com
